services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart: always
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - user-management-api_db_vol:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.development
    ports:
      - 8080:80
    volumes:
      - pgadmin-vol:/var/lib/pgadmin

volumes:
  user-management-api_db_vol: {}
  pgadmin-vol: {}
