services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart: always
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - user-management-api_db_vol:/bitnami/postgresql

volumes:
  user-management-api_db_vol: {}
